In [1]:
import pandas as pd

In [2]:
#url for draft and combine (2016-2020)

combine2020 = 'https://www.pro-football-reference.com/draft/2020-combine.htm#combine'
combine2019 = 'https://www.pro-football-reference.com/draft/2019-combine.htm'
combine2018 = 'https://www.pro-football-reference.com/draft/2018-combine.htm'
combine2017 = 'https://www.pro-football-reference.com/draft/2017-combine.htm'
combine2016 =  'https://www.pro-football-reference.com/draft/2016-combine.htm'
draft2020 = 'https://en.wikipedia.org/wiki/2020_NFL_Draft'
draft2019 = 'https://en.wikipedia.org/wiki/2019_NFL_Draft'
draft2018 = 'https://en.wikipedia.org/wiki/2018_NFL_Draft'
draft2017 = 'https://en.wikipedia.org/wiki/2017_NFL_Draft'
draft2016 = 'https://en.wikipedia.org/wiki/2016_NFL_Draft'

In [3]:
combine_2020 = pd.read_html(combine2020)
combine_2019 = pd.read_html(combine2019)
combine_2018 = pd.read_html(combine2018)
combine_2017 = pd.read_html(combine2017)
combine_2016 = pd.read_html(combine2016)
draft_2020 = pd.read_html(draft2020)
draft_2019 = pd.read_html(draft2019)
draft_2018 = pd.read_html(draft2018)
draft_2017 = pd.read_html(draft2017)
draft_2016 = pd.read_html(draft2016)

In [4]:
type(combine_2020)

list

In [5]:
len(combine_2020)

1

In [6]:
combinedf2020 = combine_2020[0]
combinedf2019 = combine_2019[0]
combinedf2018 = combine_2018[0]
combinedf2017 = combine_2017[0]
combinedf2016 = combine_2016[0]
draftdf2020 = draft_2020[4]
draftdf2019 = draft_2019[4]
draftdf2018 = draft_2018[4]
draftdf2017 = draft_2017[4]
draftdf2016 = draft_2016[4]

In [7]:
combinedf2020

,Player,Pos,School,College,Ht,Wt,40yd,Vertical,Bench,Broad Jump,3Cone,Shuttle,Drafted (tm/rnd/yr)
0,Trey Adams,OL,Washington,College Stats,6-8,318,5.60,24.5,NaN,92,NaN,NaN,NaN
1,Hakeem Adeniji,OL,Kansas,College Stats,6-4,302,5.17,34.0,26,115,NaN,NaN,Cincinnati Bengals / 6th / 180th pick / 2020
2,McTelvin Agim,DL,Arkansas,College Stats,6-3,309,4.98,NaN,27,NaN,NaN,NaN,Denver Broncos / 3rd / 95th pick / 2020
3,Salvon Ahmed,RB,Washington,College Stats,5-11,197,4.62,34.5,NaN,120,NaN,NaN,NaN
4,Brandon Aiyuk,WR,Arizona State,College Stats,6-0,205,4.50,40.0,11,128,NaN,NaN,San Francisco 49ers / 1st / 25th pick / 2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,D.J. Wonnum,DL,South Carolina,College Stats,6-5,258,4.73,34.5,20,123,7.25,4.44,Minnesota Vikings / 4th / 117th pick / 2020
339,Dom Wood-Anderson,TE,Tennessee,College Stats,6-4,261,4.92,35.0,NaN,119,NaN,NaN,NaN
340,David Woodward,LB,Utah State,College Stats,6-2,230,4.79,33.5,16,114,7.34,4.37,NaN
341,Chase Young,DL,Ohio State,College Stats,6-5,264,NaN,NaN,NaN,NaN,NaN,NaN,Washington Football Team / 1st / 2nd pick / 2020
342,Jabari Zuniga,DL,Florida,College Stats,6-3,264,4.64,33.0,29,127,NaN,NaN,New York Jets / 3rd / 79th pick / 2020

In [11]:
combine_df_2020 = combinedf2020.drop(columns = ['Drafted (tm/rnd/yr)', 'College'], axis=1)
combine_df_2019 = combinedf2019.drop(columns = ['Drafted (tm/rnd/yr)', 'College'], axis=1)
combine_df_2018 = combinedf2018.drop(columns = ['Drafted (tm/rnd/yr)', 'College'], axis=1)
combine_df_2017 = combinedf2017.drop(columns = ['Drafted (tm/rnd/yr)', 'College'], axis=1)
combine_df_2016 = combinedf2016.drop(columns = ['Drafted (tm/rnd/yr)', 'College'], axis=1)

combine_df_2020

,Player,Pos,School,Ht,Wt,40yd,Vertical,Bench,Broad Jump,3Cone,Shuttle
0,Trey Adams,OL,Washington,6-8,318,5.60,24.5,NaN,92,NaN,NaN
1,Hakeem Adeniji,OL,Kansas,6-4,302,5.17,34.0,26,115,NaN,NaN
2,McTelvin Agim,DL,Arkansas,6-3,309,4.98,NaN,27,NaN,NaN,NaN
3,Salvon Ahmed,RB,Washington,5-11,197,4.62,34.5,NaN,120,NaN,NaN
4,Brandon Aiyuk,WR,Arizona State,6-0,205,4.50,40.0,11,128,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
338,D.J. Wonnum,DL,South Carolina,6-5,258,4.73,34.5,20,123,7.25,4.44
339,Dom Wood-Anderson,TE,Tennessee,6-4,261,4.92,35.0,NaN,119,NaN,NaN
340,David Woodward,LB,Utah State,6-2,230,4.79,33.5,16,114,7.34,4.37
341,Chase Young,DL,Ohio State,6-5,264,NaN,NaN,NaN,NaN,NaN,NaN
342,Jabari Zuniga,DL,Florida,6-3,264,4.64,33.0,29,127,NaN,NaN

In [18]:
draftdf2016 = draftdf2016.drop(columns = ['Notes', 'Unnamed: 0'])
draftdf2016 = draftdf2016.rename(columns = {"Pick #": "Pick_no"})

KeyError: "['Notes' 'Unnamed: 0'] not found in axis"

In [20]:
draft_df_2016 = draftdf2016
draft_df_2016

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Los Angeles Rams,Jared GoffÂ â€,QB,California,Pac-12
1,1,2.0,Philadelphia Eagles,Carson WentzÂ â€,QB,North Dakota State,MVFC
2,1,3.0,San Diego Chargers,Joey BosaÂ â€,DE,Ohio State,Big Ten
3,1,4.0,Dallas Cowboys,Ezekiel ElliottÂ â€,RB,Ohio State,Big Ten
4,1,5.0,Jacksonville Jaguars,Jalen RamseyÂ â€,CB,Florida State,ACC
...,...,...,...,...,...,...,...
252,7,249.0,San Francisco 49ers,Prince Charles Iworah,CB,Western Kentucky,C-USA
253,7,250.0,Cleveland Browns,Scooby Wright,LB,Arizona,Pac-12
254,7,251.0,Philadelphia Eagles,Joe Walker,LB,Oregon,Pac-12
255,7,252.0,Carolina Panthers,Beau Sandland,TE,Montana State,Big Sky
256,7,253.0,Tennessee Titans,Kalan Reed,CB,Southern Miss,C-USA

In [21]:
draftdf2017 = draftdf2017.drop(columns = ['Notes', 'Unnamed: 0'])
draftdf2017 = draftdf2017.rename(columns = {"Pick #": "Pick_no"})
draftdf2017

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Cleveland Browns,Myles GarrettÂ â€,DE,Texas A&M,SEC
1,1,2.0,Chicago Bears,Mitchell TrubiskyÂ â€,QB,North Carolina,ACC
2,1,3.0,San Francisco 49ers,Solomon Thomas,DE,Stanford,Pac-12
3,1,4.0,Jacksonville Jaguars,Leonard Fournette,RB,LSU,SEC
4,1,5.0,Tennessee Titans,Corey Davis,WR,Western Michigan,MAC
...,...,...,...,...,...,...,...
252,7,249.0,Seattle Seahawks,Chris Carson,RB,Oklahoma State,Big 12
253,7,250.0,Detroit Lions,Pat O'Connor,DE,Eastern Michigan,MAC
254,7*,251.0,Cincinnati Bengals,Mason Schreck,TE,Buffalo,MAC
255,7*,252.0,Cleveland Browns,Matthew Dayes,RB,NC State,ACC
256,7*,253.0,Denver Broncos,Chad Kelly,QB,Ole Miss,SEC

In [22]:
draftdf2018 = draftdf2018.drop(columns = ['Notes', 'Unnamed: 0'])
draftdf2018 = draftdf2018.rename(columns = {"Pick #": "Pick_no"})
draftdf2018

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1,Cleveland Browns,Baker Mayfield,QB,Oklahoma,Big 12
1,1,2,New York Giants,Saquon BarkleyÂ â€,RB,Penn State,Big Ten
2,1,3,New York Jets,Sam Darnold,QB,USC,Pac-12
3,1,4,Cleveland Browns,Denzel WardÂ â€,CB,Ohio State,Big Ten
4,1,5,Denver Broncos,Bradley ChubbÂ â€,LB,NC State,ACC
...,...,...,...,...,...,...,...
251,7*,252,Cincinnati Bengals,Rod Taylor,G,Ole Miss,SEC
252,7*,253,Cincinnati Bengals,Auden Tate,WR,Florida State,ACC
253,7*,254,Arizona Cardinals,Korey Cunningham,OT,Cincinnati,The American
254,7*,255,Buffalo Bills,Austin Proehl,WR,North Carolina,ACC
255,7*,256,Washington Redskins,Trey Quinn,WR,SMU,The American

In [23]:
draftdf2019 = draftdf2019.drop(columns = ['Notes', 'Unnamed: 0'])
draftdf2019 = draftdf2019.rename(columns = {"Pick #": "Pick_no"})
draftdf2019

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Arizona Cardinals,Kyler MurrayÂ â€,QB,Oklahoma,Big 12
1,1,2.0,San Francisco 49ers,Nick BosaÂ â€,DE,Ohio State,Big Ten
2,1,3.0,New York Jets,Quinnen Williams,DT,Alabama,SEC
3,1,4.0,Oakland Raiders,Clelin Ferrell,DE,Clemson,ACC
4,1,5.0,Tampa Bay Buccaneers,Devin White,ILB,LSU,SEC
...,...,...,...,...,...,...,...
251,7*,250.0,Minnesota Vikings,Austin Cutting,LS,Air Force,MW
252,7*,251.0,Los Angeles Rams,Dakota Allen,LB,Texas Tech,Big 12
253,7*,252.0,New England Patriots,Ken Webster,CB,Ole Miss,SEC
254,7*,253.0,Washington Redskins,Jordan Brailford,DE,Oklahoma State,Big 12
255,7*,254.0,Arizona Cardinals,Caleb Wilson,TE,UCLA,Pac-12

In [24]:
draftdf2020 = draftdf2020.drop(columns = ['Notes', 'Unnamed: 0'])
draftdf2020 = draftdf2020.rename(columns = {"Pick #": "Pick_no"})
draftdf2020

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Cincinnati Bengals,Joe Burrow,QB,LSU,SEC
1,1,2.0,Washington Redskins,Chase YoungÂ â€,DE,Ohio State,Big Ten
2,1,3.0,Detroit Lions,Jeff Okudah,CB,Ohio State,Big Ten
3,1,4.0,New York Giants,Andrew Thomas,OT,Georgia,SEC
4,1,5.0,Miami Dolphins,Tua Tagovailoa,QB,Alabama,SEC
...,...,...,...,...,...,...,...
251,7*,251.0,Seattle Seahawks,Stephen Sullivan,TE,LSU,SEC
252,7*,252.0,Denver Broncos,Tyrie Cleveland,WR,Florida,SEC
253,7*,253.0,Minnesota Vikings,Kyle Hinton,C,Washburn,MIAA
254,7*,254.0,Denver Broncos,Derrek Tuszka,DE,North Dakota State,MVFC
255,7*,255.0,New York Giants,Tae Crowder,LB,Georgia,SEC

In [25]:
draft_df_2020 = draftdf2020
draft_df_2019 = draftdf2019
draft_df_2018 = draftdf2018
draft_df_2017 = draftdf2017
draft_df_2016 = draftdf2016
draft_df_2016

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Los Angeles Rams,Jared GoffÂ â€,QB,California,Pac-12
1,1,2.0,Philadelphia Eagles,Carson WentzÂ â€,QB,North Dakota State,MVFC
2,1,3.0,San Diego Chargers,Joey BosaÂ â€,DE,Ohio State,Big Ten
3,1,4.0,Dallas Cowboys,Ezekiel ElliottÂ â€,RB,Ohio State,Big Ten
4,1,5.0,Jacksonville Jaguars,Jalen RamseyÂ â€,CB,Florida State,ACC
...,...,...,...,...,...,...,...
252,7,249.0,San Francisco 49ers,Prince Charles Iworah,CB,Western Kentucky,C-USA
253,7,250.0,Cleveland Browns,Scooby Wright,LB,Arizona,Pac-12
254,7,251.0,Philadelphia Eagles,Joe Walker,LB,Oregon,Pac-12
255,7,252.0,Carolina Panthers,Beau Sandland,TE,Montana State,Big Sky
256,7,253.0,Tennessee Titans,Kalan Reed,CB,Southern Miss,C-USA

In [27]:
draft_df_2020['year']='2020'
draft_df_2019['year']='2019'
draft_df_2018['year']='2018'
draft_df_2017['year']='2017'
draft_df_2016['year']='2016'
combine_df_2020['year']='2020'
combine_df_2019['year']='2019'
combine_df_2018['year']='2018'
combine_df_2017['year']='2017'
combine_df_2016['year']='2016'
draft_df_2016

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.,year
0,1,1.0,Los Angeles Rams,Jared GoffÂ â€,QB,California,Pac-12,2016
1,1,2.0,Philadelphia Eagles,Carson WentzÂ â€,QB,North Dakota State,MVFC,2016
2,1,3.0,San Diego Chargers,Joey BosaÂ â€,DE,Ohio State,Big Ten,2016
3,1,4.0,Dallas Cowboys,Ezekiel ElliottÂ â€,RB,Ohio State,Big Ten,2016
4,1,5.0,Jacksonville Jaguars,Jalen RamseyÂ â€,CB,Florida State,ACC,2016
...,...,...,...,...,...,...,...,...
252,7,249.0,San Francisco 49ers,Prince Charles Iworah,CB,Western Kentucky,C-USA,2016
253,7,250.0,Cleveland Browns,Scooby Wright,LB,Arizona,Pac-12,2016
254,7,251.0,Philadelphia Eagles,Joe Walker,LB,Oregon,Pac-12,2016
255,7,252.0,Carolina Panthers,Beau Sandland,TE,Montana State,Big Sky,2016
256,7,253.0,Tennessee Titans,Kalan Reed,CB,Southern Miss,C-USA,2016

In [28]:
combine_df = combine_df_2020.append(combine_df_2019,ignore_index=True,verify_integrity=True)
combine_df = combine_df.append(combine_df_2018,ignore_index=True,verify_integrity=True)
combine_df = combine_df.append(combine_df_2017,ignore_index=True,verify_integrity=True)
combine_df = combine_df.append(combine_df_2016,ignore_index=True,verify_integrity=True)
combine_df

,Player,Pos,School,Ht,Wt,40yd,Vertical,Bench,Broad Jump,3Cone,Shuttle,year
0,Trey Adams,OL,Washington,6-8,318,5.60,24.5,NaN,92,NaN,NaN,2020
1,Hakeem Adeniji,OL,Kansas,6-4,302,5.17,34.0,26,115,NaN,NaN,2020
2,McTelvin Agim,DL,Arkansas,6-3,309,4.98,NaN,27,NaN,NaN,NaN,2020
3,Salvon Ahmed,RB,Washington,5-11,197,4.62,34.5,NaN,120,NaN,NaN,2020
4,Brandon Aiyuk,WR,Arizona State,6-0,205,4.50,40.0,11,128,NaN,NaN,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
1694,Daryl Worley,CB,West Virginia,6-1,204,4.64,35.5,14,123,6.98,4.15,2016
1695,Connor Wujciak,DT,Boston Col.,6-2,291,4.91,34.5,22,117,7.32,4.27,2016
1696,Tavon Young,CB,Temple,5-9,183,4.46,34.5,9,118,6.80,3.93,2016
1697,Avery Young,OT,Auburn,6-5,328,5.39,NaN,NaN,NaN,8.22,4.91,2016
1698,Anthony Zettel,DT,Penn State,6-4,277,4.81,30.5,28,109,7.63,4.39,2016

In [32]:
draft_df = draft_df_2020.append(draft_df_2019,ignore_index=True,verify_integrity=True)
draft_df = draft_df.append(draft_df_2018,ignore_index=True,verify_integrity=True)
draft_df = draft_df.append(draft_df_2017,ignore_index=True,verify_integrity=True)
draft_df = draft_df.append(draft_df_2016,ignore_index=True,verify_integrity=True)
draft_df = draft_df.rename(columns = {"Pos.": "Pos", "College": "School"})
draft_df

,Rnd.,Pick_no,NFL team,Player,Pos,School,Conf.,year
0,1,1.0,Cincinnati Bengals,Joe Burrow,QB,LSU,SEC,2020
1,1,2.0,Washington Redskins,Chase YoungÂ â€,DE,Ohio State,Big Ten,2020
2,1,3.0,Detroit Lions,Jeff Okudah,CB,Ohio State,Big Ten,2020
3,1,4.0,New York Giants,Andrew Thomas,OT,Georgia,SEC,2020
4,1,5.0,Miami Dolphins,Tua Tagovailoa,QB,Alabama,SEC,2020
...,...,...,...,...,...,...,...,...
1277,7,249.0,San Francisco 49ers,Prince Charles Iworah,CB,Western Kentucky,C-USA,2016
1278,7,250.0,Cleveland Browns,Scooby Wright,LB,Arizona,Pac-12,2016
1279,7,251.0,Philadelphia Eagles,Joe Walker,LB,Oregon,Pac-12,2016
1280,7,252.0,Carolina Panthers,Beau Sandland,TE,Montana State,Big Sky,2016
1281,7,253.0,Tennessee Titans,Kalan Reed,CB,Southern Miss,C-USA,2016

In [30]:
player = combine_df['Player']
pos = combine_df['Pos']
school = combine_df['School']

combine_player_df = {"player":player,
                "pos":pos,
                "school":school}
combine_player_df = pd.DataFrame(combine_player_df)
combine_player_df

              player pos         school
0         Trey Adams  OL     Washington
1     Hakeem Adeniji  OL         Kansas
2      McTelvin Agim  DL       Arkansas
3       Salvon Ahmed  RB     Washington
4      Brandon Aiyuk  WR  Arizona State
...              ...  ..            ...
1694    Daryl Worley  CB  West Virginia
1695  Connor Wujciak  DT    Boston Col.
1696     Tavon Young  CB         Temple
1697     Avery Young  OT         Auburn
1698  Anthony Zettel  DT     Penn State

[1699 rows x 3 columns]

In [33]:
player = draft_df['Player']
pos = draft_df['Pos']
school = draft_df['School']

draft_player_df = {"player":player,
                "pos":pos,
                "school":school}
draft_player_df = pd.DataFrame(draft_player_df)
draft_player_df

                     player pos            school
0                Joe Burrow  QB               LSU
1             Chase YoungÂ â€   DE        Ohio State
2               Jeff Okudah  CB        Ohio State
3             Andrew Thomas  OT           Georgia
4            Tua Tagovailoa  QB           Alabama
...                     ...  ..               ...
1277  Prince Charles Iworah  CB  Western Kentucky
1278          Scooby Wright  LB           Arizona
1279             Joe Walker  LB            Oregon
1280          Beau Sandland  TE     Montana State
1281             Kalan Reed  CB     Southern Miss

[1282 rows x 3 columns]

In [34]:
combined_df = pd.concat([draft_player_df, combine_player_df])
combined_df

              player pos         school
0         Joe Burrow  QB            LSU
1      Chase YoungÂ â€   DE     Ohio State
2        Jeff Okudah  CB     Ohio State
3      Andrew Thomas  OT        Georgia
4     Tua Tagovailoa  QB        Alabama
...              ...  ..            ...
1694    Daryl Worley  CB  West Virginia
1695  Connor Wujciak  DT    Boston Col.
1696     Tavon Young  CB         Temple
1697     Avery Young  OT         Auburn
1698  Anthony Zettel  DT     Penn State

[2981 rows x 3 columns]

In [35]:
combined_df = combined_df.drop_duplicates(subset=None, keep='first')
combined_df

              player pos       school
0         Joe Burrow  QB          LSU
1      Chase YoungÂ â€   DE   Ohio State
2        Jeff Okudah  CB   Ohio State
3      Andrew Thomas  OT      Georgia
4     Tua Tagovailoa  QB      Alabama
...              ...  ..          ...
1692    Josh Woodrum  QB      Liberty
1693   Antwaun Woods  NT          USC
1695  Connor Wujciak  DT  Boston Col.
1697     Avery Young  OT       Auburn
1698  Anthony Zettel  DT   Penn State

[2346 rows x 3 columns]