In [1]:
#Import Dependencies
import pandas as pd

Scrap the data from the web using pandas

In [2]:
#Assign 2016-2020 URL's to variables
url_2016 = 'https://en.wikipedia.org/wiki/2016_NFL_Draft'
url_2017 = 'https://en.wikipedia.org/wiki/2017_NFL_Draft'
url_2018 = 'https://en.wikipedia.org/wiki/2018_NFL_Draft'
url_2019 = 'https://en.wikipedia.org/wiki/2019_NFL_Draft'
url_2020 = 'https://en.wikipedia.org/wiki/2020_NFL_Draft'

In [3]:
#Read in 2016-2020 URL's into table's using Pandas
table_2016 = pd.read_html(url_2016)
table_2017 = pd.read_html(url_2017)
table_2018 = pd.read_html(url_2018)
table_2019 = pd.read_html(url_2019)
table_2020 = pd.read_html(url_2020)

In [4]:
#Check the variable type
type(table_2016)

list

In [5]:
#Check the Length of the table
len(table_2016)

13

Clean the Data Using Pandas

In [6]:
#Convert the tables to a dataframe
df_2016_combine = table_2016[4]
df_2017_combine = table_2017[4]
df_2018_combine = table_2018[4]
df_2019_combine = table_2019[4]
df_2020_combine = table_2020[4]

In [7]:
#Clean the 2016 Dataframe
df_2016_combine = df_2016_combine.drop(columns = ['Unnamed: 0', 'Notes'])
df_2016_combine = df_2016_combine.rename(columns = {"Pick #": "Pick_no"})
df_2016_combine

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Los Angeles Rams,Jared Goff †,QB,California,Pac-12
1,1,2.0,Philadelphia Eagles,Carson Wentz †,QB,North Dakota State,MVFC
2,1,3.0,San Diego Chargers,Joey Bosa †,DE,Ohio State,Big Ten
3,1,4.0,Dallas Cowboys,Ezekiel Elliott †,RB,Ohio State,Big Ten
4,1,5.0,Jacksonville Jaguars,Jalen Ramsey †,CB,Florida State,ACC
...,...,...,...,...,...,...,...
252,7,249.0,San Francisco 49ers,Prince Charles Iworah,CB,Western Kentucky,C-USA
253,7,250.0,Cleveland Browns,Scooby Wright,LB,Arizona,Pac-12
254,7,251.0,Philadelphia Eagles,Joe Walker,LB,Oregon,Pac-12
255,7,252.0,Carolina Panthers,Beau Sandland,TE,Montana State,Big Sky
256,7,253.0,Tennessee Titans,Kalan Reed,CB,Southern Miss,C-USA

In [8]:
#Clean the 2017 Dataframe
df_2017_combine = df_2017_combine.drop(columns = ['Unnamed: 0', 'Notes'])
df_2017_combine = df_2017_combine.rename(columns = {"Pick #": "Pick_no"})
df_2017_combine

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Cleveland Browns,Myles Garrett †,DE,Texas A&M,SEC
1,1,2.0,Chicago Bears,Mitchell Trubisky †,QB,North Carolina,ACC
2,1,3.0,San Francisco 49ers,Solomon Thomas,DE,Stanford,Pac-12
3,1,4.0,Jacksonville Jaguars,Leonard Fournette,RB,LSU,SEC
4,1,5.0,Tennessee Titans,Corey Davis,WR,Western Michigan,MAC
...,...,...,...,...,...,...,...
252,7,249.0,Seattle Seahawks,Chris Carson,RB,Oklahoma State,Big 12
253,7,250.0,Detroit Lions,Pat O'Connor,DE,Eastern Michigan,MAC
254,7*,251.0,Cincinnati Bengals,Mason Schreck,TE,Buffalo,MAC
255,7*,252.0,Cleveland Browns,Matthew Dayes,RB,NC State,ACC
256,7*,253.0,Denver Broncos,Chad Kelly,QB,Ole Miss,SEC

In [9]:
#Clean the 2018 Dataframe
df_2018_combine = df_2018_combine.drop(columns = ['Unnamed: 0', 'Notes'])
df_2018_combine = df_2018_combine.rename(columns = {"Pick #": "Pick_no"})
df_2018_combine

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1,Cleveland Browns,Baker Mayfield,QB,Oklahoma,Big 12
1,1,2,New York Giants,Saquon Barkley †,RB,Penn State,Big Ten
2,1,3,New York Jets,Sam Darnold,QB,USC,Pac-12
3,1,4,Cleveland Browns,Denzel Ward †,CB,Ohio State,Big Ten
4,1,5,Denver Broncos,Bradley Chubb †,LB,NC State,ACC
...,...,...,...,...,...,...,...
251,7*,252,Cincinnati Bengals,Rod Taylor,G,Ole Miss,SEC
252,7*,253,Cincinnati Bengals,Auden Tate,WR,Florida State,ACC
253,7*,254,Arizona Cardinals,Korey Cunningham,OT,Cincinnati,The American
254,7*,255,Buffalo Bills,Austin Proehl,WR,North Carolina,ACC
255,7*,256,Washington Redskins,Trey Quinn,WR,SMU,The American

In [10]:
#Clean the 2019 Dataframe
df_2019_combine = df_2019_combine.drop(columns = ['Unnamed: 0', 'Notes'])
df_2019_combine = df_2019_combine.rename(columns = {"Pick #": "Pick_no"})
df_2019_combine

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Arizona Cardinals,Kyler Murray †,QB,Oklahoma,Big 12
1,1,2.0,San Francisco 49ers,Nick Bosa †,DE,Ohio State,Big Ten
2,1,3.0,New York Jets,Quinnen Williams,DT,Alabama,SEC
3,1,4.0,Oakland Raiders,Clelin Ferrell,DE,Clemson,ACC
4,1,5.0,Tampa Bay Buccaneers,Devin White,ILB,LSU,SEC
...,...,...,...,...,...,...,...
251,7*,250.0,Minnesota Vikings,Austin Cutting,LS,Air Force,MW
252,7*,251.0,Los Angeles Rams,Dakota Allen,LB,Texas Tech,Big 12
253,7*,252.0,New England Patriots,Ken Webster,CB,Ole Miss,SEC
254,7*,253.0,Washington Redskins,Jordan Brailford,DE,Oklahoma State,Big 12
255,7*,254.0,Arizona Cardinals,Caleb Wilson,TE,UCLA,Pac-12

In [11]:
#Clean the 2020 Dataframe
df_2020_combine = df_2020_combine.drop(columns = ['Unnamed: 0', 'Notes'])
df_2020_combine = df_2020_combine.rename(columns = {"Pick #": "Pick_no"})
df_2020_combine

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.
0,1,1.0,Cincinnati Bengals,Joe Burrow,QB,LSU,SEC
1,1,2.0,Washington Redskins,Chase Young †,DE,Ohio State,Big Ten
2,1,3.0,Detroit Lions,Jeff Okudah,CB,Ohio State,Big Ten
3,1,4.0,New York Giants,Andrew Thomas,OT,Georgia,SEC
4,1,5.0,Miami Dolphins,Tua Tagovailoa,QB,Alabama,SEC
...,...,...,...,...,...,...,...
251,7*,251.0,Seattle Seahawks,Stephen Sullivan,TE,LSU,SEC
252,7*,252.0,Denver Broncos,Tyrie Cleveland,WR,Florida,SEC
253,7*,253.0,Minnesota Vikings,Kyle Hinton,C,Washburn,MIAA
254,7*,254.0,Denver Broncos,Derrek Tuszka,DE,North Dakota State,MVFC
255,7*,255.0,New York Giants,Tae Crowder,LB,Georgia,SEC

Append the data into a single DataFrame to post it to the database

In [12]:
# Add a year column for data storage Purposes
df_2016_combine['year']='2016'
df_2017_combine['year']='2017'
df_2018_combine['year']='2018'
df_2019_combine['year']='2019'
df_2020_combine['year']='2020'
df_2016_combine

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.,year
0,1,1.0,Los Angeles Rams,Jared Goff †,QB,California,Pac-12,2016
1,1,2.0,Philadelphia Eagles,Carson Wentz †,QB,North Dakota State,MVFC,2016
2,1,3.0,San Diego Chargers,Joey Bosa †,DE,Ohio State,Big Ten,2016
3,1,4.0,Dallas Cowboys,Ezekiel Elliott †,RB,Ohio State,Big Ten,2016
4,1,5.0,Jacksonville Jaguars,Jalen Ramsey †,CB,Florida State,ACC,2016
...,...,...,...,...,...,...,...,...
252,7,249.0,San Francisco 49ers,Prince Charles Iworah,CB,Western Kentucky,C-USA,2016
253,7,250.0,Cleveland Browns,Scooby Wright,LB,Arizona,Pac-12,2016
254,7,251.0,Philadelphia Eagles,Joe Walker,LB,Oregon,Pac-12,2016
255,7,252.0,Carolina Panthers,Beau Sandland,TE,Montana State,Big Sky,2016
256,7,253.0,Tennessee Titans,Kalan Reed,CB,Southern Miss,C-USA,2016

In [13]:
# Append the 5 years DataFrames into one dataframe for storage purposes
draft_df = df_2020_combine.append(df_2019_combine,ignore_index=True,verify_integrity=True)
draft_df = draft_df.append(df_2018_combine,ignore_index=True,verify_integrity=True)
draft_df = draft_df.append(df_2017_combine,ignore_index=True,verify_integrity=True)
draft_df = draft_df.append(df_2016_combine,ignore_index=True,verify_integrity=True)

draft_df

,Rnd.,Pick_no,NFL team,Player,Pos.,College,Conf.,year
0,1,1.0,Cincinnati Bengals,Joe Burrow,QB,LSU,SEC,2020
1,1,2.0,Washington Redskins,Chase Young †,DE,Ohio State,Big Ten,2020
2,1,3.0,Detroit Lions,Jeff Okudah,CB,Ohio State,Big Ten,2020
3,1,4.0,New York Giants,Andrew Thomas,OT,Georgia,SEC,2020
4,1,5.0,Miami Dolphins,Tua Tagovailoa,QB,Alabama,SEC,2020
...,...,...,...,...,...,...,...,...
1277,7,249.0,San Francisco 49ers,Prince Charles Iworah,CB,Western Kentucky,C-USA,2016
1278,7,250.0,Cleveland Browns,Scooby Wright,LB,Arizona,Pac-12,2016
1279,7,251.0,Philadelphia Eagles,Joe Walker,LB,Oregon,Pac-12,2016
1280,7,252.0,Carolina Panthers,Beau Sandland,TE,Montana State,Big Sky,2016
1281,7,253.0,Tennessee Titans,Kalan Reed,CB,Southern Miss,C-USA,2016